//
//  LocalizationManager.swift
//  FitMetricsLog
//
//  Single-file localization — supports English and German.
//  Usage: L.key  or  L("key")
//

import SwiftUI
import Combine

// MARK: - Language
enum AppLanguage: String, CaseIterable, Codable {
    case english = "en"
    case german  = "de"

    var displayName: String {
        switch self {
        case .english: return "English"
        case .german:  return "Deutsch"
        }
    }
    var flag: String {
        switch self {
        case .english: return "🇬🇧"
        case .german:  return "🇩🇪"
        }
    }
}

// MARK: - Manager
class LocalizationManager: ObservableObject {
    static let shared = LocalizationManager()
    private let key = "appLanguage_v1"

    @Published var language: AppLanguage = .english {
        didSet { UserDefaults.standard.set(language.rawValue, forKey: key) }
    }

    init() {
        if let raw = UserDefaults.standard.string(forKey: key),
           let lang = AppLanguage(rawValue: raw) {
            language = lang
        }
    }

    func t(_ key: LKey) -> String {
        switch language {
        case .english: return key.en
        case .german:  return key.de
        }
    }
}

/// Shorthand global accessor
func L(_ key: LKey) -> String { LocalizationManager.shared.t(key) }

// MARK: - String Keys
enum LKey {
    // MARK: Tab Bar
    case tabHome, tabExercises, tabLog, tabPrograms, tabMore

    // MARK: Common
    case cancel, save, done, back, delete, edit, add, close, apply, reset, restore
    case confirm, yes, no, ok
    case all, custom, filter, search, notes, preview

    // MARK: Actions
    case addPhoto, removePhoto, tapToChangePhoto, chooseFromLibrary, takePhoto
    case selectAll, deselectAll, deleteSelected

    // MARK: Home
    case myProgress, yourProgress, workoutsLogged, totalVolume, noDataYet
    case noDataForPeriod, logWorkoutsFirst, unleash, letsTrainEmoji
    case volumeMuscleBreakdown, allTime, insights, analyticsInsights

    // MARK: Exercises
    case exercises, exerciseName, exerciseDesc, addExercise, editExercise, newExercise
    case noExercisesYet, tapToAddExercise, inYourLibrary, exerciseSaved
    case muscleGroup, muscleGroups, muscleBreakdown, primary, secondary
    case difficulty, duration, sets, reps, weight, weightKg, videoURL, tags
    case beginner, intermediate, advanced, watchVideo, photos
    case deleteExercise, deleteExerciseMsg, historyKept
    case tapToViewHoldToDelete, tapTrashToDelete

    // MARK: Workout Log
    case workoutLog, sessions, logSession, noLogsYet, tapToLog
    case newSession, editSession, deleteSession, deleteSessionQ
    case sessionNotes, startWorkout, loadFromProgram
    case estOneRM, maxWeight, totalVol, reorderHint
    case duplicateSession, exportLog, selectSessions, selectAtLeastOne
    case exportFormat, exportSessions, willBeIncluded

    // MARK: Programs
    case programs, workoutPlans, noPrograms, createProgram, tapToCreate
    case programName, newProgram, saveProgram, editProgram, deleteProgram, deleteProgramQ
    case generateProgram, regenerate, autoGenTitle, selectMusclesCount
    case selectAtLeastOneMuscle, exercisesAvailable, totalExercises
    case autoGenerated

    // MARK: Profile
    case profile, editProfile, displayName, fitmetricslogMember
    case manageMuscleoGroups, importExport, aboutApp
    case clearAllData, clearAllQ, clearEverything, clearAllMsg
    case sessionCount, kgLifted

    // MARK: Muscle Group Editor
    case muscleGroupsTitle, builtInGroups, myCustomGroups, hiddenGroups
    case hiddenGroupsHint, newGroup, editGroup, renameGroup, groupName
    case groupNamePlaceholder, deleteGroup, deleteGroupMsg, deleteBuiltInMsg
    case allBuiltInHidden, tapToAddCustom
    case colorLabel, iconLabel, customColor, hexCode, presets
    case enterValidHex, originalLabel

    // MARK: About
    case about, developer, email, website, appDesc, version

    // MARK: Import / Export
    case importData, exportData, importFromFile, selectJson
    case importMergeNote, importSuccess, importFail, importError
    case exportCreatesJson

    // MARK: Settings / Language
    case language, chooseLanguage, appLanguage

    // MARK: Alerts
    case cannotUndo, thisCannotBeUndone
    case deletePhotoQ, deletePhotoMsg
    case builtInHiddenMsg, noAffectLogs

    // MARK: Filters
    case filtered, rangeAllTime, rangeWeek, rangeMonth, rangeYear

    // MARK: Chart
    case chartColor, barChart, lineChart, volume

    var en: String {
        switch self {
        case .tabHome: return "Home"
        case .tabExercises: return "Exercises"
        case .tabLog: return "Log"
        case .tabPrograms: return "Programs"
        case .tabMore: return "More"
        case .cancel: return "Cancel"
        case .save: return "Save"
        case .done: return "Done"
        case .back: return "Back"
        case .delete: return "Delete"
        case .edit: return "Edit"
        case .add: return "Add"
        case .close: return "Close"
        case .apply: return "Apply"
        case .reset: return "Reset"
        case .restore: return "Restore"
        case .confirm: return "Confirm"
        case .yes: return "Yes"
        case .no: return "No"
        case .ok: return "OK"
        case .all: return "All"
        case .custom: return "Custom"
        case .filter: return "Filter"
        case .search: return "Search"
        case .notes: return "Notes"
        case .preview: return "Preview"
        case .addPhoto: return "Add Photo"
        case .removePhoto: return "Remove Photo"
        case .tapToChangePhoto: return "Tap to change photo"
        case .chooseFromLibrary: return "Choose from Library"
        case .takePhoto: return "Take Photo"
        case .selectAll: return "All"
        case .deselectAll: return "Deselect All"
        case .deleteSelected: return "Delete Selected"
        case .myProgress: return "My Progress"
        case .yourProgress: return "Your Progress"
        case .workoutsLogged: return "Workouts Logged"
        case .totalVolume: return "Total Volume"
        case .noDataYet: return "No data yet"
        case .noDataForPeriod: return "No data for this period"
        case .logWorkoutsFirst: return "Log workouts to see your volume chart"
        case .unleash: return "Unleash Your Potential\nwith FitMetricsLog"
        case .letsTrainEmoji: return "Let's Train 💪"
        case .volumeMuscleBreakdown: return "Volume & muscle breakdown"
        case .allTime: return "all time"
        case .insights: return "Insights"
        case .analyticsInsights: return "Analytics & Insights"
        case .exercises: return "Exercises"
        case .exerciseName: return "Exercise Name"
        case .exerciseDesc: return "Description"
        case .addExercise: return "Add Exercise"
        case .editExercise: return "Edit Exercise"
        case .newExercise: return "New Exercise"
        case .noExercisesYet: return "No exercises yet"
        case .tapToAddExercise: return "Tap + to add your first exercise"
        case .inYourLibrary: return "in library"
        case .exerciseSaved: return "Exercise saved!"
        case .muscleGroup: return "Muscle Group"
        case .muscleGroups: return "Muscle Groups"
        case .muscleBreakdown: return "Muscle Breakdown"
        case .primary: return "Primary"
        case .secondary: return "Secondary"
        case .difficulty: return "Difficulty"
        case .duration: return "Duration"
        case .sets: return "Sets"
        case .reps: return "Reps"
        case .weight: return "Weight"
        case .weightKg: return "Weight (kg)"
        case .videoURL: return "Video URL"
        case .tags: return "Tags"
        case .beginner: return "Beginner"
        case .intermediate: return "Intermediate"
        case .advanced: return "Advanced"
        case .watchVideo: return "Watch Video"
        case .photos: return "Photos"
        case .deleteExercise: return "Delete Exercise"
        case .deleteExerciseMsg: return "Delete Exercise?"
        case .historyKept: return "Workout history for this exercise will be kept."
        case .tapToViewHoldToDelete: return "Tap to view · Hold to delete"
        case .tapTrashToDelete: return "Tap 🗑 to delete this photo"
        case .workoutLog: return "Workout Log"
        case .sessions: return "sessions"
        case .logSession: return "Log Session"
        case .noLogsYet: return "No sessions yet"
        case .tapToLog: return "Tap + to log your first workout"
        case .newSession: return "New Session"
        case .editSession: return "Edit Session"
        case .deleteSession: return "Delete Session"
        case .deleteSessionQ: return "Delete Session?"
        case .sessionNotes: return "Session Notes"
        case .startWorkout: return "Start Workout"
        case .loadFromProgram: return "Load from Program"
        case .estOneRM: return "Est. 1RM"
        case .maxWeight: return "max weight"
        case .totalVol: return "total volume"
        case .reorderHint: return "Drag ≡ to reorder"
        case .duplicateSession: return "Duplicate Session"
        case .exportLog: return "Export Log"
        case .selectSessions: return "Select sessions"
        case .selectAtLeastOne: return "Select at least one session"
        case .exportFormat: return "Export Format"
        case .exportSessions: return "Export Sessions"
        case .willBeIncluded: return "will be included in the export"
        case .programs: return "Programs"
        case .workoutPlans: return "workout plans"
        case .noPrograms: return "No programs yet"
        case .createProgram: return "Create Program"
        case .tapToCreate: return "Create a workout plan to organize your exercises"
        case .programName: return "Program Name"
        case .newProgram: return "New Program"
        case .saveProgram: return "Save Program"
        case .editProgram: return "Edit Program"
        case .deleteProgram: return "Delete Program"
        case .deleteProgramQ: return "Delete Program?"
        case .generateProgram: return "Generate Program"
        case .regenerate: return "Regenerate"
        case .autoGenTitle: return "Auto-Generate Program"
        case .selectMusclesCount: return "Select Muscle Groups & Exercise Count"
        case .selectAtLeastOneMuscle: return "Select at least one muscle group"
        case .exercisesAvailable: return "exercises available"
        case .totalExercises: return "Total Exercises"
        case .autoGenerated: return "Auto-generated"
        case .profile: return "Profile"
        case .editProfile: return "Edit Profile"
        case .displayName: return "Display Name"
        case .fitmetricslogMember: return "FitMetricsLog Member"
        case .manageMuscleoGroups: return "Manage Muscle Groups"
        case .importExport: return "Import / Export Data"
        case .aboutApp: return "About FitMetricsLog"
        case .clearAllData: return "Clear All Data"
        case .clearAllQ: return "Clear All Data?"
        case .clearEverything: return "Clear Everything"
        case .clearAllMsg: return "This will permanently delete all exercises, workout logs, and programs. This cannot be undone."
        case .sessionCount: return "Sessions"
        case .kgLifted: return "kg lifted"
        case .muscleGroupsTitle: return "Muscle Groups"
        case .builtInGroups: return "Built-in Groups"
        case .myCustomGroups: return "My Custom Groups"
        case .hiddenGroups: return "Hidden Groups"
        case .hiddenGroupsHint: return "Hidden Groups (tap to restore)"
        case .newGroup: return "New Group"
        case .editGroup: return "Edit Group"
        case .renameGroup: return "Rename Group"
        case .groupName: return "Group Name"
        case .groupNamePlaceholder: return "e.g. Glutes, Upper Chest..."
        case .deleteGroup: return "Delete Group"
        case .deleteGroupMsg: return "This will not affect existing workout logs."
        case .deleteBuiltInMsg: return "This built-in group will be hidden. You can restore it from the Hidden Groups section."
        case .allBuiltInHidden: return "All built-in groups are hidden"
        case .tapToAddCustom: return "Tap + to add a custom group"
        case .colorLabel: return "Color"
        case .iconLabel: return "Icon"
        case .customColor: return "Custom Color"
        case .hexCode: return "Hex Code"
        case .presets: return "Presets"
        case .enterValidHex: return "Enter a valid 6-digit hex"
        case .originalLabel: return "original"
        case .about: return "About"
        case .developer: return "Developer"
        case .email: return "Email"
        case .website: return "Website"
        case .appDesc: return "FitMetricsLog is your personal workout companion. Log exercises, track progress, build custom programs, and analyze your performance over time."
        case .version: return "Version 1.0.0"
        case .importData: return "Import"
        case .exportData: return "Export"
        case .importFromFile: return "Import from File"
        case .selectJson: return "Select a .json file"
        case .importMergeNote: return "Import merges the data — existing items won't be duplicated."
        case .importSuccess: return "Import successful"
        case .importFail: return "Import failed"
        case .importError: return "Could not access the file."
        case .exportCreatesJson: return "Export creates a JSON file. Import merges the data — existing items won't be duplicated."
        case .language: return "Language"
        case .chooseLanguage: return "Choose Language"
        case .appLanguage: return "App Language"
        case .cannotUndo: return "This action cannot be undone."
        case .thisCannotBeUndone: return "This cannot be undone."
        case .deletePhotoQ: return "Delete this photo?"
        case .deletePhotoMsg: return "This cannot be undone."
        case .builtInHiddenMsg: return "This built-in group will be hidden. You can restore it from the Hidden Groups section."
        case .noAffectLogs: return "This will not affect existing workout logs."
        case .filtered: return "Filtered"
        case .rangeAllTime: return "All Time"
        case .rangeWeek: return "Week"
        case .rangeMonth: return "Month"
        case .rangeYear: return "Year"
        case .chartColor: return "Chart Color"
        case .barChart: return "Bar"
        case .lineChart: return "Line"
        case .volume: return "volume"
        }
    }

    var de: String {
        switch self {
        case .tabHome: return "Start"
        case .tabExercises: return "Übungen"
        case .tabLog: return "Protokoll"
        case .tabPrograms: return "Programme"
        case .tabMore: return "Mehr"
        case .cancel: return "Abbrechen"
        case .save: return "Speichern"
        case .done: return "Fertig"
        case .back: return "Zurück"
        case .delete: return "Löschen"
        case .edit: return "Bearbeiten"
        case .add: return "Hinzufügen"
        case .close: return "Schließen"
        case .apply: return "Übernehmen"
        case .reset: return "Zurücksetzen"
        case .restore: return "Wiederherstellen"
        case .confirm: return "Bestätigen"
        case .yes: return "Ja"
        case .no: return "Nein"
        case .ok: return "OK"
        case .all: return "Alle"
        case .custom: return "Benutzerdefiniert"
        case .filter: return "Filter"
        case .search: return "Suche"
        case .notes: return "Notizen"
        case .preview: return "Vorschau"
        case .addPhoto: return "Foto hinzufügen"
        case .removePhoto: return "Foto entfernen"
        case .tapToChangePhoto: return "Tippen zum Ändern"
        case .chooseFromLibrary: return "Aus Bibliothek wählen"
        case .takePhoto: return "Foto aufnehmen"
        case .selectAll: return "Alle"
        case .deselectAll: return "Alle abwählen"
        case .deleteSelected: return "Auswahl löschen"
        case .myProgress: return "Mein Fortschritt"
        case .yourProgress: return "Dein Fortschritt"
        case .workoutsLogged: return "Trainings"
        case .totalVolume: return "Gesamtvolumen"
        case .noDataYet: return "Noch keine Daten"
        case .noDataForPeriod: return "Keine Daten für diesen Zeitraum"
        case .logWorkoutsFirst: return "Protokolliere ein Training für das Volumendiagramm"
        case .unleash: return "Entfessle dein Potenzial\nmit FitMetricsLog"
        case .letsTrainEmoji: return "Los geht's 💪"
        case .volumeMuscleBreakdown: return "Volumen & Muskelgruppen"
        case .allTime: return "gesamt"
        case .insights: return "Einblicke"
        case .analyticsInsights: return "Analysen & Einblicke"
        case .exercises: return "Übungen"
        case .exerciseName: return "Übungsname"
        case .exerciseDesc: return "Beschreibung"
        case .addExercise: return "Übung hinzufügen"
        case .editExercise: return "Übung bearbeiten"
        case .newExercise: return "Neue Übung"
        case .noExercisesYet: return "Noch keine Übungen"
        case .tapToAddExercise: return "Tippe + um deine erste Übung hinzuzufügen"
        case .inYourLibrary: return "in der Bibliothek"
        case .exerciseSaved: return "Übung gespeichert!"
        case .muscleGroup: return "Muskelgruppe"
        case .muscleGroups: return "Muskelgruppen"
        case .muscleBreakdown: return "Muskelanalyse"
        case .primary: return "Primär"
        case .secondary: return "Sekundär"
        case .difficulty: return "Schwierigkeit"
        case .duration: return "Dauer"
        case .sets: return "Sätze"
        case .reps: return "Wdh."
        case .weight: return "Gewicht"
        case .weightKg: return "Gewicht (kg)"
        case .videoURL: return "Video-URL"
        case .tags: return "Tags"
        case .beginner: return "Anfänger"
        case .intermediate: return "Fortgeschritten"
        case .advanced: return "Experte"
        case .watchVideo: return "Video ansehen"
        case .photos: return "Fotos"
        case .deleteExercise: return "Übung löschen"
        case .deleteExerciseMsg: return "Übung löschen?"
        case .historyKept: return "Das Trainingsprotokoll bleibt erhalten."
        case .tapToViewHoldToDelete: return "Tippen zum Ansehen · Halten zum Löschen"
        case .tapTrashToDelete: return "🗑 tippen zum Löschen"
        case .workoutLog: return "Trainingsprotokoll"
        case .sessions: return "Einheiten"
        case .logSession: return "Einheit protokollieren"
        case .noLogsYet: return "Noch keine Einheiten"
        case .tapToLog: return "Tippe + für dein erstes Training"
        case .newSession: return "Neue Einheit"
        case .editSession: return "Einheit bearbeiten"
        case .deleteSession: return "Einheit löschen"
        case .deleteSessionQ: return "Einheit löschen?"
        case .sessionNotes: return "Einheitsnotizen"
        case .startWorkout: return "Training starten"
        case .loadFromProgram: return "Aus Programm laden"
        case .estOneRM: return "Gesch. 1WH-Max"
        case .maxWeight: return "Max. Gewicht"
        case .totalVol: return "Gesamtvolumen"
        case .reorderHint: return "≡ halten zum Sortieren"
        case .duplicateSession: return "Einheit duplizieren"
        case .exportLog: return "Protokoll exportieren"
        case .selectSessions: return "Einheiten auswählen"
        case .selectAtLeastOne: return "Mindestens eine Einheit auswählen"
        case .exportFormat: return "Exportformat"
        case .exportSessions: return "Einheiten exportieren"
        case .willBeIncluded: return "wird exportiert"
        case .programs: return "Programme"
        case .workoutPlans: return "Trainingspläne"
        case .noPrograms: return "Noch keine Programme"
        case .createProgram: return "Programm erstellen"
        case .tapToCreate: return "Erstelle einen Trainingsplan für deine Übungen"
        case .programName: return "Programmname"
        case .newProgram: return "Neues Programm"
        case .saveProgram: return "Programm speichern"
        case .editProgram: return "Programm bearbeiten"
        case .deleteProgram: return "Programm löschen"
        case .deleteProgramQ: return "Programm löschen?"
        case .generateProgram: return "Programm generieren"
        case .regenerate: return "Neu generieren"
        case .autoGenTitle: return "Programm automatisch erstellen"
        case .selectMusclesCount: return "Muskelgruppen & Übungsanzahl wählen"
        case .selectAtLeastOneMuscle: return "Mindestens eine Muskelgruppe wählen"
        case .exercisesAvailable: return "Übungen verfügbar"
        case .totalExercises: return "Übungen gesamt"
        case .autoGenerated: return "Automatisch erstellt"
        case .profile: return "Profil"
        case .editProfile: return "Profil bearbeiten"
        case .displayName: return "Anzeigename"
        case .fitmetricslogMember: return "FitMetricsLog-Mitglied"
        case .manageMuscleoGroups: return "Muskelgruppen verwalten"
        case .importExport: return "Importieren / Exportieren"
        case .aboutApp: return "Über FitMetricsLog"
        case .clearAllData: return "Alle Daten löschen"
        case .clearAllQ: return "Alle Daten löschen?"
        case .clearEverything: return "Alles löschen"
        case .clearAllMsg: return "Alle Übungen, Protokolle und Programme werden dauerhaft gelöscht. Dies kann nicht rückgängig gemacht werden."
        case .sessionCount: return "Einheiten"
        case .kgLifted: return "kg gestemmt"
        case .muscleGroupsTitle: return "Muskelgruppen"
        case .builtInGroups: return "Integrierte Gruppen"
        case .myCustomGroups: return "Eigene Gruppen"
        case .hiddenGroups: return "Ausgeblendete Gruppen"
        case .hiddenGroupsHint: return "Ausgeblendet (tippen zum Wiederherstellen)"
        case .newGroup: return "Neue Gruppe"
        case .editGroup: return "Gruppe bearbeiten"
        case .renameGroup: return "Gruppe umbenennen"
        case .groupName: return "Gruppenname"
        case .groupNamePlaceholder: return "z. B. Gesäß, Obere Brust..."
        case .deleteGroup: return "Gruppe löschen"
        case .deleteGroupMsg: return "Bestehende Trainingseinträge bleiben erhalten."
        case .deleteBuiltInMsg: return "Diese Gruppe wird ausgeblendet. Du kannst sie im Bereich 'Ausgeblendet' wiederherstellen."
        case .allBuiltInHidden: return "Alle integrierten Gruppen sind ausgeblendet"
        case .tapToAddCustom: return "Tippe + um eine eigene Gruppe hinzuzufügen"
        case .colorLabel: return "Farbe"
        case .iconLabel: return "Symbol"
        case .customColor: return "Benutzerdefinierte Farbe"
        case .hexCode: return "Hex-Code"
        case .presets: return "Voreinstellungen"
        case .enterValidHex: return "Gib einen gültigen 6-stelligen Hex-Code ein"
        case .originalLabel: return "Original"
        case .about: return "Über die App"
        case .developer: return "Entwickler"
        case .email: return "E-Mail"
        case .website: return "Webseite"
        case .appDesc: return "FitMetricsLog ist dein persönlicher Trainingsbegleiter. Protokolliere Übungen, verfolge deinen Fortschritt, erstelle eigene Programme und analysiere deine Leistung."
        case .version: return "Version 1.0.0"
        case .importData: return "Importieren"
        case .exportData: return "Exportieren"
        case .importFromFile: return "Aus Datei importieren"
        case .selectJson: return "Eine .json-Datei auswählen"
        case .importMergeNote: return "Import fügt Daten zusammen – vorhandene Einträge werden nicht dupliziert."
        case .importSuccess: return "Import erfolgreich"
        case .importFail: return "Import fehlgeschlagen"
        case .importError: return "Auf die Datei konnte nicht zugegriffen werden."
        case .exportCreatesJson: return "Export erstellt eine JSON-Datei. Import fügt Daten zusammen – keine Duplikate."
        case .language: return "Sprache"
        case .chooseLanguage: return "Sprache wählen"
        case .appLanguage: return "App-Sprache"
        case .cannotUndo: return "Diese Aktion kann nicht rückgängig gemacht werden."
        case .thisCannotBeUndone: return "Kann nicht rückgängig gemacht werden."
        case .deletePhotoQ: return "Dieses Foto löschen?"
        case .deletePhotoMsg: return "Kann nicht rückgängig gemacht werden."
        case .builtInHiddenMsg: return "Diese Gruppe wird ausgeblendet und kann wiederhergestellt werden."
        case .noAffectLogs: return "Bestehende Trainingseinträge bleiben erhalten."
        case .filtered: return "Gefiltert"
        case .rangeAllTime: return "Gesamt"
        case .rangeWeek: return "Woche"
        case .rangeMonth: return "Monat"
        case .rangeYear: return "Jahr"
        case .chartColor: return "Diagrammfarbe"
        case .barChart: return "Balken"
        case .lineChart: return "Linie"
        case .volume: return "Volumen"
        }
    }
}
